export const defaultNotificationWorkspaceId =
  "00000000-0000-0000-0000-000000000001";

export const notificationCategories = [
  "calendar",
  "sales",
  "rentals",
  "leads",
  "messages",
  "documents",
  "contracts",
  "tasks",
  "requests",
  "system",
  "workspace",
  "data_quality",
  "map_location",
] as const;

export const notificationPriorities = ["low", "normal", "high", "urgent"] as const;

export const notificationStatuses = [
  "unread",
  "read",
  "archived",
  "dismissed",
  "snoozed",
] as const;

export const notificationEntityTypes = [
  "property",
  "sale_property",
  "rental_property",
  "lead",
  "message_thread",
  "appointment",
  "calendar_event",
  "meeting",
  "client",
  "deal",
  "task",
  "request",
  "document",
  "contract",
  "user",
  "workspace",
  "import_job",
  "system",
] as const;

export const notificationTypes = [
  "meeting_reminder",
  "visit_scheduled",
  "visit_starts_soon",
  "visit_overdue",
  "visit_cancelled",
  "visit_rescheduled",
  "new_assigned_lead",
  "lead_assigned",
  "lead_follow_up_due",
  "lead_follow_up_overdue",
  "duplicate_lead_detected",
  "property_update",
  "property_assigned",
  "property_published",
  "property_missing_media",
  "property_missing_coordinates",
  "property_price_changed",
  "property_status_changed",
  "rental_contract_ending",
  "follow_up_reminder",
  "contract_reminder",
  "contract_pending_signature",
  "contract_expiring_soon",
  "document_uploaded",
  "document_rejected",
  "document_requires_review",
  "task_assigned",
  "task_due_soon",
  "task_overdue",
  "request_assigned",
  "request_matched",
  "system_alert",
  "workspace_alert",
  "data_quality_warning",
  "map_location_warning",
  "message",
  "mention",
  "property_message",
  "lead_message",
  "meeting_message",
  "deal_room_message",
  "task_created_from_message",
] as const;
